[server]
maxUploadSize = 100
enableStaticServing = true
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3949ab"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1a1a2e"
font = "sans serif"

[runner]
fastReruns = true
