[server]
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = true
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3949ab"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1a1a2e"
font = "sans serif"

[runner]
fastReruns = true
